/*
* Autogenerated code. Please DO NOT EDIT 
*/

package wavecrest.catalog;
import java.util.Map;
import java.util.HashMap;

import wavecrest.usermanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.billpay.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.orchestration.pimanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.orchestration.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.usermanager.dto.*;
import wavecrest.billpay.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.integration.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.billpay.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.integration.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.billpay.enums.*;
import wavecrest.program.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.usermanager.dto.*;
import wavecrest.billpay.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.orchestration.enums.*;
import wavecrest.billpay.enums.*;
import wavecrest.program.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.program.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.orchestration.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.orchestration.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.billpay.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.usermanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.program.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.postman.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.billpay.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.cardmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.pimanager.enums.*;
import wavecrest.orchestration.enums.*;
import wavecrest.foundation.enums.*;
import wavecrest.txnmanager.enums.*;
import wavecrest.program.enums.*;
import wavecrest.program.enums.*;


public class WCEnumLookup {
  private static Map enumTypeValuesMap = new HashMap<String,Map>(10);
  static {
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.NationalIdentifierType", wavecrest.usermanager.enums.NationalIdentifierType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.MerchantCategory", wavecrest.usermanager.enums.MerchantCategory.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.FISUKMessage", wavecrest.cardmanager.enums.FISUKMessage.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.ReferenceAccountType", wavecrest.billpay.enums.ReferenceAccountType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BoxStatus", wavecrest.cardmanager.enums.BoxStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.VerificationCodeStatus", wavecrest.usermanager.enums.VerificationCodeStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.DebitAccount", wavecrest.txnmanager.enums.DebitAccount.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.SecurityAnswerAlgorithm", wavecrest.program.enums.SecurityAnswerAlgorithm.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.PaymentFrequency", wavecrest.usermanager.enums.PaymentFrequency.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CoreProcessorOrderDetailStatus", wavecrest.cardmanager.enums.CoreProcessorOrderDetailStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.Industry", wavecrest.program.enums.Industry.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.ContentType", wavecrest.postman.enums.ContentType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.orchestration.pimanager.enums.SettelementType", wavecrest.orchestration.pimanager.enums.SettelementType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.PasswordType", wavecrest.usermanager.enums.PasswordType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.Status", wavecrest.program.enums.Status.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.CapabilityType", wavecrest.program.enums.CapabilityType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.RequestTypeStatus", wavecrest.cardmanager.enums.RequestTypeStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.SettlementSource", wavecrest.program.enums.SettlementSource.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.orchestration.enums.ResourceMethod", wavecrest.orchestration.enums.ResourceMethod.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.StockRequestStatus", wavecrest.cardmanager.enums.StockRequestStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.Status", wavecrest.foundation.enums.Status.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.dto.PrincipalType", wavecrest.usermanager.dto.PrincipalType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.ServiceProviderType", wavecrest.billpay.enums.ServiceProviderType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.AlertType", wavecrest.postman.enums.AlertType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.OperationStatus", wavecrest.program.enums.OperationStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.ZipCodeStatus", wavecrest.program.enums.ZipCodeStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.UserAccessType", wavecrest.usermanager.enums.UserAccessType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.PaymentProcessorEnum", wavecrest.pimanager.enums.PaymentProcessorEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.OperationFlagStatus", wavecrest.cardmanager.enums.OperationFlagStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.TxnConstants", wavecrest.txnmanager.enums.TxnConstants.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.AutoUpgradeCardsStatus", wavecrest.cardmanager.enums.AutoUpgradeCardsStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardFulfillmentOrderStatus", wavecrest.cardmanager.enums.CardFulfillmentOrderStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardsMonthlyFeesStatus", wavecrest.cardmanager.enums.CardsMonthlyFeesStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.AuthenticationKeys", wavecrest.foundation.enums.AuthenticationKeys.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.CardForm", wavecrest.program.enums.CardForm.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.PinChangeFeesStatus", wavecrest.cardmanager.enums.PinChangeFeesStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.RequestCodeType", wavecrest.program.enums.RequestCodeType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.LinkStatus", wavecrest.usermanager.enums.LinkStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BarCodeGenerationAlgorithmEnum", wavecrest.cardmanager.enums.BarCodeGenerationAlgorithmEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.InstrumentStatus", wavecrest.pimanager.enums.InstrumentStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.LoginUserIdType", wavecrest.program.enums.LoginUserIdType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.TermsAndConditionsType", wavecrest.program.enums.TermsAndConditionsType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardIssuanceType", wavecrest.cardmanager.enums.CardIssuanceType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.DeliveryType", wavecrest.cardmanager.enums.DeliveryType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.UpgradeCardType", wavecrest.cardmanager.enums.UpgradeCardType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.AlertCategory", wavecrest.postman.enums.AlertCategory.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.InventoryMethodEnum", wavecrest.cardmanager.enums.InventoryMethodEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.SystemAccountType", wavecrest.txnmanager.enums.SystemAccountType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.AlertStatus", wavecrest.postman.enums.AlertStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.DecisionType", wavecrest.program.enums.DecisionType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.IDDocumentType", wavecrest.usermanager.enums.IDDocumentType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BillPayRequestType", wavecrest.cardmanager.enums.BillPayRequestType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.FormFactor", wavecrest.program.enums.FormFactor.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.EntityReferenceType", wavecrest.program.enums.EntityReferenceType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.VerificationCodeType", wavecrest.usermanager.enums.VerificationCodeType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.BuddyAddModeEnum", wavecrest.usermanager.enums.BuddyAddModeEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.CsrActionType", wavecrest.program.enums.CsrActionType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.integration.enums.ProcessorCodeMappingType", wavecrest.integration.enums.ProcessorCodeMappingType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.UserRegistrationType", wavecrest.usermanager.enums.UserRegistrationType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.DecisionType", wavecrest.postman.enums.DecisionType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.PrincipalConfigMode", wavecrest.usermanager.enums.PrincipalConfigMode.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.FirmType", wavecrest.program.enums.FirmType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.AccessLevel", wavecrest.postman.enums.AccessLevel.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardFulfillmentStatus", wavecrest.cardmanager.enums.CardFulfillmentStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.NotesReasonsEnum", wavecrest.program.enums.NotesReasonsEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.FISUSCardStatus", wavecrest.cardmanager.enums.FISUSCardStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.VerificationTypeStatus", wavecrest.usermanager.enums.VerificationTypeStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.ACHNocCodes", wavecrest.pimanager.enums.ACHNocCodes.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.DisputeTxnStatus", wavecrest.postman.enums.DisputeTxnStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.TicketPriority", wavecrest.usermanager.enums.TicketPriority.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.LoginPasswordType", wavecrest.program.enums.LoginPasswordType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FeeType", wavecrest.txnmanager.enums.FeeType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.BatchType", wavecrest.program.enums.BatchType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.AdjustmentType", wavecrest.cardmanager.enums.AdjustmentType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.DisputeAction", wavecrest.txnmanager.enums.DisputeAction.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.VerificationCodeFormat", wavecrest.usermanager.enums.VerificationCodeFormat.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.BankAccountType", wavecrest.pimanager.enums.BankAccountType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.TicketStatus", wavecrest.usermanager.enums.TicketStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.CrDrMode", wavecrest.txnmanager.enums.CrDrMode.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.ServiceCategory", wavecrest.billpay.enums.ServiceCategory.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.AlertName", wavecrest.postman.enums.AlertName.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.UserAddressType", wavecrest.program.enums.UserAddressType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.MemberShipLevel", wavecrest.usermanager.enums.MemberShipLevel.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.PartnerType", wavecrest.foundation.enums.PartnerType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.TransactionType", wavecrest.usermanager.enums.TransactionType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.AgentType", wavecrest.usermanager.enums.AgentType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.ProgramConfigurationCategory", wavecrest.program.enums.ProgramConfigurationCategory.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardJournal", wavecrest.cardmanager.enums.CardJournal.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.UserStatus", wavecrest.usermanager.enums.UserStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FeeGroup", wavecrest.txnmanager.enums.FeeGroup.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.VerificationType", wavecrest.usermanager.enums.VerificationType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardAction", wavecrest.cardmanager.enums.CardAction.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.AdditionalCardType", wavecrest.program.enums.AdditionalCardType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.InventoryAPIEnum", wavecrest.cardmanager.enums.InventoryAPIEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FeeValueIdentifier", wavecrest.txnmanager.enums.FeeValueIdentifier.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.AccessLevel", wavecrest.program.enums.AccessLevel.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.SchedulerJobType", wavecrest.program.enums.SchedulerJobType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.SchedulePaymentStatus", wavecrest.usermanager.enums.SchedulePaymentStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.UserCardPreferenceRefId", wavecrest.cardmanager.enums.UserCardPreferenceRefId.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.Gender", wavecrest.usermanager.enums.Gender.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.TxnReqQueueStatus", wavecrest.txnmanager.enums.TxnReqQueueStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardFormFactor", wavecrest.cardmanager.enums.CardFormFactor.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.BatchFileStatus", wavecrest.program.enums.BatchFileStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BPCardProgramMappingConfigType", wavecrest.cardmanager.enums.BPCardProgramMappingConfigType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.VerificationMethod", wavecrest.pimanager.enums.VerificationMethod.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.DocumentVerificationDetailsStatus", wavecrest.usermanager.enums.DocumentVerificationDetailsStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.integration.enums.FISUKCardStatus", wavecrest.integration.enums.FISUKCardStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.AccountModeOfOperation", wavecrest.pimanager.enums.AccountModeOfOperation.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.PaymentMode", wavecrest.billpay.enums.PaymentMode.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.CsrActionCategoryType", wavecrest.program.enums.CsrActionCategoryType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.ACHReturnCodes", wavecrest.pimanager.enums.ACHReturnCodes.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BillPayVendor", wavecrest.cardmanager.enums.BillPayVendor.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.FeeApplicable", wavecrest.program.enums.FeeApplicable.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.VerificationStatus", wavecrest.usermanager.enums.VerificationStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardDistributorOperationType", wavecrest.cardmanager.enums.CardDistributorOperationType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.TxnStatus", wavecrest.txnmanager.enums.TxnStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.Salutation", wavecrest.usermanager.enums.Salutation.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.IDologyOutcome", wavecrest.usermanager.enums.IDologyOutcome.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.NonMonTxnStatus", wavecrest.txnmanager.enums.NonMonTxnStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.ProcessorIncomingTxnType", wavecrest.txnmanager.enums.ProcessorIncomingTxnType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.AlertPriority", wavecrest.postman.enums.AlertPriority.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.ActiveMQJMXAttribute", wavecrest.foundation.enums.ActiveMQJMXAttribute.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.IDType", wavecrest.usermanager.enums.IDType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FeeScheduleType", wavecrest.txnmanager.enums.FeeScheduleType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.FulfillmentOrderDetailStatus", wavecrest.cardmanager.enums.FulfillmentOrderDetailStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.IdentityStatus", wavecrest.usermanager.enums.IdentityStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.InventoryEntityEnum", wavecrest.cardmanager.enums.InventoryEntityEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.FileStatus", wavecrest.cardmanager.enums.FileStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.dto.AdminUserStatus", wavecrest.usermanager.dto.AdminUserStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.ServiceStatus", wavecrest.billpay.enums.ServiceStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.TxnAccountStatus", wavecrest.txnmanager.enums.TxnAccountStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.orchestration.enums.OrchestrationEnum", wavecrest.orchestration.enums.OrchestrationEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.ServiceType", wavecrest.billpay.enums.ServiceType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.UserType", wavecrest.program.enums.UserType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.DisputeTxnType", wavecrest.postman.enums.DisputeTxnType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.ECIResponseCodes", wavecrest.program.enums.ECIResponseCodes.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.RequestFundsType", wavecrest.txnmanager.enums.RequestFundsType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.TxnType", wavecrest.txnmanager.enums.TxnType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CoreProcessOrderStatus", wavecrest.cardmanager.enums.CoreProcessOrderStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.RecordType", wavecrest.cardmanager.enums.RecordType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BulkCardsStatusChange", wavecrest.cardmanager.enums.BulkCardsStatusChange.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.orchestration.enums.IVRPriority", wavecrest.orchestration.enums.IVRPriority.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.TxnAccountType", wavecrest.txnmanager.enums.TxnAccountType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.NotificationProvider", wavecrest.postman.enums.NotificationProvider.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardDistributorSize", wavecrest.cardmanager.enums.CardDistributorSize.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.BuddyNotificationType", wavecrest.usermanager.enums.BuddyNotificationType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.OptionType", wavecrest.postman.enums.OptionType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.ReturnBatchRecordStatus", wavecrest.program.enums.ReturnBatchRecordStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardProgramPackageMappingConfigType", wavecrest.cardmanager.enums.CardProgramPackageMappingConfigType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FxProvider", wavecrest.txnmanager.enums.FxProvider.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.CsrApprovalStatus", wavecrest.program.enums.CsrApprovalStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BundleStatus", wavecrest.cardmanager.enums.BundleStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.orchestration.enums.CardCreationEnum", wavecrest.orchestration.enums.CardCreationEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.CardScheme", wavecrest.program.enums.CardScheme.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.DocumentSide", wavecrest.program.enums.DocumentSide.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.SubscriptionType", wavecrest.billpay.enums.SubscriptionType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.TimeInterval", wavecrest.usermanager.enums.TimeInterval.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.RemoteAccountType", wavecrest.txnmanager.enums.RemoteAccountType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.FulfillmentOrderStatus", wavecrest.cardmanager.enums.FulfillmentOrderStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FISUSTxnType", wavecrest.txnmanager.enums.FISUSTxnType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.BuddyStatus", wavecrest.usermanager.enums.BuddyStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.Severity", wavecrest.foundation.enums.Severity.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.usermanager.enums.KYC", wavecrest.usermanager.enums.KYC.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.PayMode", wavecrest.pimanager.enums.PayMode.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.DocumentType", wavecrest.program.enums.DocumentType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.NotificationType", wavecrest.postman.enums.NotificationType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.Infrastructure", wavecrest.foundation.enums.Infrastructure.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.PasswordSecurityAlgorithm", wavecrest.program.enums.PasswordSecurityAlgorithm.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.ChannelSubType", wavecrest.foundation.enums.ChannelSubType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FeeScheduleStatus", wavecrest.txnmanager.enums.FeeScheduleStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.StockRequestConfigStatus", wavecrest.cardmanager.enums.StockRequestConfigStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.ChannelType", wavecrest.program.enums.ChannelType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.AddressType", wavecrest.program.enums.AddressType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.AlertReasonCodeEnum", wavecrest.foundation.enums.AlertReasonCodeEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.BinStatus", wavecrest.cardmanager.enums.BinStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.TemplateType", wavecrest.postman.enums.TemplateType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardStatus", wavecrest.cardmanager.enums.CardStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.postman.enums.CurrentStatus", wavecrest.postman.enums.CurrentStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.LogAnalytics", wavecrest.foundation.enums.LogAnalytics.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.billpay.enums.SubscriptionStatus", wavecrest.billpay.enums.SubscriptionStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.ReqQueueStatus", wavecrest.program.enums.ReqQueueStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.IssuerStatus", wavecrest.cardmanager.enums.IssuerStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.Source", wavecrest.program.enums.Source.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardProgramStatus", wavecrest.cardmanager.enums.CardProgramStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CardDistributorStatus", wavecrest.cardmanager.enums.CardDistributorStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.MakerCheckerApprovalStatus", wavecrest.program.enums.MakerCheckerApprovalStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.DisputedTransactionReason", wavecrest.txnmanager.enums.DisputedTransactionReason.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.AVSResult", wavecrest.pimanager.enums.AVSResult.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.BatchRecordStatus", wavecrest.program.enums.BatchRecordStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.CountryStatus", wavecrest.program.enums.CountryStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.CorsOperation", wavecrest.cardmanager.enums.CorsOperation.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.ProgramConfigurationStatus", wavecrest.program.enums.ProgramConfigurationStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.cardmanager.enums.InventoryUpdatedSourceEnum", wavecrest.cardmanager.enums.InventoryUpdatedSourceEnum.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.InstrumentType", wavecrest.program.enums.InstrumentType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.RequestType", wavecrest.program.enums.RequestType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.InstrumentConstants", wavecrest.pimanager.enums.InstrumentConstants.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.pimanager.enums.InstrumentVerificationStatus", wavecrest.pimanager.enums.InstrumentVerificationStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.orchestration.enums.DisputeFormType", wavecrest.orchestration.enums.DisputeFormType.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.foundation.enums.AlertVerificationStatus", wavecrest.foundation.enums.AlertVerificationStatus.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.txnmanager.enums.FeeCalcMode", wavecrest.txnmanager.enums.FeeCalcMode.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.OperationResult", wavecrest.program.enums.OperationResult.getMap());
    
      
      
      enumTypeValuesMap.put("wavecrest.program.enums.RequestCodeConfigType", wavecrest.program.enums.RequestCodeConfigType.getMap());
    
  }

	public static Object lookupEnumValue (int value) {
    Object val = null;
   
    
    
    val = wavecrest.usermanager.enums.NationalIdentifierType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.MerchantCategory.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.FISUKMessage.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.ReferenceAccountType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BoxStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.VerificationCodeStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.DebitAccount.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.SecurityAnswerAlgorithm.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.PaymentFrequency.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CoreProcessorOrderDetailStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.Industry.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.ContentType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.orchestration.pimanager.enums.SettelementType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.PasswordType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.Status.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.CapabilityType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.RequestTypeStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.SettlementSource.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.orchestration.enums.ResourceMethod.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.StockRequestStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.Status.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.dto.PrincipalType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.ServiceProviderType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.AlertType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.OperationStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.ZipCodeStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.UserAccessType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.PaymentProcessorEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.OperationFlagStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.TxnConstants.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.AutoUpgradeCardsStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardFulfillmentOrderStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardsMonthlyFeesStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.AuthenticationKeys.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.CardForm.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.PinChangeFeesStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.RequestCodeType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.LinkStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BarCodeGenerationAlgorithmEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.InstrumentStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.LoginUserIdType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.TermsAndConditionsType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardIssuanceType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.DeliveryType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.UpgradeCardType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.AlertCategory.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.InventoryMethodEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.SystemAccountType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.AlertStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.DecisionType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.IDDocumentType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BillPayRequestType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.FormFactor.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.EntityReferenceType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.VerificationCodeType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.BuddyAddModeEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.CsrActionType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.integration.enums.ProcessorCodeMappingType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.UserRegistrationType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.DecisionType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.PrincipalConfigMode.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.FirmType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.AccessLevel.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardFulfillmentStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.NotesReasonsEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.FISUSCardStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.VerificationTypeStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.ACHNocCodes.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.DisputeTxnStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.TicketPriority.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.LoginPasswordType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FeeType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.BatchType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.AdjustmentType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.DisputeAction.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.VerificationCodeFormat.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.BankAccountType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.TicketStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.CrDrMode.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.ServiceCategory.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.AlertName.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.UserAddressType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.MemberShipLevel.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.PartnerType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.TransactionType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.AgentType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.ProgramConfigurationCategory.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardJournal.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.UserStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FeeGroup.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.VerificationType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardAction.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.AdditionalCardType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.InventoryAPIEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FeeValueIdentifier.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.AccessLevel.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.SchedulerJobType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.SchedulePaymentStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.UserCardPreferenceRefId.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.Gender.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.TxnReqQueueStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardFormFactor.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.BatchFileStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BPCardProgramMappingConfigType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.VerificationMethod.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.DocumentVerificationDetailsStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.integration.enums.FISUKCardStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.AccountModeOfOperation.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.PaymentMode.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.CsrActionCategoryType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.ACHReturnCodes.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BillPayVendor.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.FeeApplicable.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.VerificationStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardDistributorOperationType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.TxnStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.Salutation.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.IDologyOutcome.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.NonMonTxnStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.ProcessorIncomingTxnType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.AlertPriority.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.ActiveMQJMXAttribute.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.IDType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FeeScheduleType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.FulfillmentOrderDetailStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.IdentityStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.InventoryEntityEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.FileStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.dto.AdminUserStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.ServiceStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.TxnAccountStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.orchestration.enums.OrchestrationEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.ServiceType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.UserType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.DisputeTxnType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.ECIResponseCodes.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.RequestFundsType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.TxnType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CoreProcessOrderStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.RecordType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BulkCardsStatusChange.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.orchestration.enums.IVRPriority.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.TxnAccountType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.NotificationProvider.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardDistributorSize.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.BuddyNotificationType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.OptionType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.ReturnBatchRecordStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardProgramPackageMappingConfigType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FxProvider.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.CsrApprovalStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BundleStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.orchestration.enums.CardCreationEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.CardScheme.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.DocumentSide.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.SubscriptionType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.TimeInterval.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.RemoteAccountType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.FulfillmentOrderStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FISUSTxnType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.BuddyStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.Severity.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.usermanager.enums.KYC.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.PayMode.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.DocumentType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.NotificationType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.Infrastructure.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.PasswordSecurityAlgorithm.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.ChannelSubType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FeeScheduleStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.StockRequestConfigStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.ChannelType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.AddressType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.AlertReasonCodeEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.BinStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.TemplateType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.postman.enums.CurrentStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.LogAnalytics.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.billpay.enums.SubscriptionStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.ReqQueueStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.IssuerStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.Source.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardProgramStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CardDistributorStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.MakerCheckerApprovalStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.DisputedTransactionReason.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.AVSResult.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.BatchRecordStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.CountryStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.CorsOperation.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.ProgramConfigurationStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.cardmanager.enums.InventoryUpdatedSourceEnum.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.InstrumentType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.RequestType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.InstrumentConstants.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.pimanager.enums.InstrumentVerificationStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.orchestration.enums.DisputeFormType.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.foundation.enums.AlertVerificationStatus.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.txnmanager.enums.FeeCalcMode.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.OperationResult.valueOfNoException(value);
    if (val != null) return val;
   
    
    
    val = wavecrest.program.enums.RequestCodeConfigType.valueOfNoException(value);
    if (val != null) return val;
   
    return null;
	}

  /* Values of a given enum class. Return type is a map of integer keys and enum instance value */
	public static Map getEnumTypeValues (String enumclass) {
    return (Map) enumTypeValuesMap.get(enumclass);
	}
}
